Add podmonitor for external secrets and sub
GoogleCloudPlatform/oss-test-infra pull request #1004
Opened 2021-08-05 15:43 UTC by chaodaiG

Noticed that the metrics port was not added initially, which probably was the reason why podmonitor was not so happy last time

2021-08-05 15:43 UTC, chaodaiG commented
/cc @cjwagner

2021-08-05 18:24 UTC, cjwagner requested changes

2021-08-05 18:24 UTC, cjwagner commented on prow/oss/cluster/monitoring/prow_podmonitors.yaml
> +    port: prometheus
> Noticed that the metrics port was not added initially, which probably was the reason why podmonitor was not so happy last time

The pod monitor uses the `prometheus` port. I don't think 9090 is a valid port number for KES.

2021-08-05 18:27 UTC, chaodaiG commented
/hold

2021-08-18 23:09 UTC, chaodaiG commented
/close
will reopen when it's ready

2021-08-18 23:09 UTC, closed without merging