Enable github workflows retest in knative repos
GoogleCloudPlatform/oss-test-infra pull request #1400
Opened 2022-01-10 19:02 UTC by shinigambit

Make use of the feature added here kubernetes/test-infra/issues/21581

2022-01-10 19:33 UTC, chizhg reviewed
🎉 🎉 🎉  Thanks @shinigambit !!!

/ok-to-test
/lgtm
/approve

2022-01-10 19:33 UTC, chizhg commented on prow/knative/plugins.yaml
> +  - knative-prow-robot:
No need to add this since we used to add it for testing purpose. We can clean it up in follow-up PRs all together, though.

2022-01-10 19:42 UTC, chizhg requested changes

2022-01-10 19:42 UTC, chizhg commented on prow/knative/plugins.yaml
> +- repos:
It looks `repos` should be a list of strings - https://github.com/kubernetes/test-infra/blob/e47f01cbed7a926b20f1dd4b7e18d06a6d9bc146/prow/plugins/config.go#L429

2022-01-10 21:09 UTC, chaodaiG commented on prow/knative/plugins.yaml
> +  - knative:
`:` will be evaluated as part of the string matching so it won't work, dropping it would do

2022-01-10 21:17 UTC, chizhg commented
/lgtm
/approve

2022-01-10 21:18 UTC, merged

2022-01-11 15:41 UTC, shinigambit commented
Fixes knative/test-infra/issues/2992